<a href="https://colab.research.google.com/github/p-garden/dustmqdyd/blob/main/1week_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr1 = np.arange(1, 7).reshape(3, 2)
arr2 = np.arange(13, 19).reshape(3, 2)
arr3 = np.append(arr1, arr2, axis = 0)
print(arr3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [13 14]
 [15 16]
 [17 18]]


In [ ]:
arr1 = np.arange(1,25).reshape(6,4)
arr3 = np.arange(1,25).reshape(3,8)
for i in np.arange(3):
  arr2 = np.append(arr1[i],arr1[i+3],axis=0)
  arr3[i] = arr2  
print(arr3)


[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]
